name = "telescopetest-io"
account_id = "4b1c95badf17540db82cd8b431ae3eb0"
main = "worker/index.ts"
# main = "dist/_worker.js/index.js"

compatibility_date = "2025-01-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
# false = serve static assets before running worker
# true = go to worker  

[observability]
enabled = true

[[routes]]
pattern = "telescopetest.io"
custom_domain = true
# ^ this means all paths go to the worker